<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="TESTING-029" name="LMS_Scenarios.LMS_Scenario_24" tests="8" failures="0" timestamp="27 Nov 2019 13:57:17 GMT" time="392.697" errors="2">
  <testcase name="TC001_LaunchBrowser" time="8.217" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC001_PaymentVerification_BeforePayment" time="71.833" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC002_ReceiptMaker" time="101.375" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC002_ReceiptApprover" time="53.239" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC005_PaymentVerification" time="91.947" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC004_ReceiptCancel" time="66.086" classname="LMS_Scenarios.LMS_Scenario_24"/>
  <testcase name="TC005_ApproveCancelledReceipt" time="0.000" classname="LMS_Scenarios.LMS_Scenario_24">
    <error type="org.testng.TestNGException" message="
Method public static void LMS_Scenarios.LMS_Scenario_24.TC005_ApproveCancelledReceipt(java.util.Map) throws java.io.IOException requires a @DataProvider named : Receipt approver">
      <![CDATA[org.testng.TestNGException: 
Method public static void LMS_Scenarios.LMS_Scenario_24.TC005_ApproveCancelledReceipt(java.util.Map) throws java.io.IOException requires a @DataProvider named : Receipt approver
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC005_ApproveCancelledReceipt -->
  <testcase name="TC006_PaymentVerificatiion" time="0.000" classname="LMS_Scenarios.LMS_Scenario_24">
    <error type="org.testng.TestNGException" message="
Method public static void LMS_Scenarios.LMS_Scenario_24.TC006_PaymentVerificatiion(java.util.Map) throws java.io.IOException requires a @DataProvider named : Payment verification">
      <![CDATA[org.testng.TestNGException: 
Method public static void LMS_Scenarios.LMS_Scenario_24.TC006_PaymentVerificatiion(java.util.Map) throws java.io.IOException requires a @DataProvider named : Payment verification
at org.testng.internal.Parameters.findDataProvider(Parameters.java:513)
at org.testng.internal.Parameters.handleParameters(Parameters.java:691)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC006_PaymentVerificatiion -->
</testsuite> <!-- LMS_Scenarios.LMS_Scenario_24 -->
